[package]
name = "wasm-runtime"
version = "0.1.0"
authors = ["Adam Snaider <adsnaider@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-parse = {path = "third_party/wasm-parse"}
thiserror = "1.0"
